---
title: "業績一覧"
---

## 著書

- 藤井美和・小杉考司・李政元(編著)(2005).福祉・心理・看護のテキストマイニング入門中央法規.
- 小杉考司(2006).心理--論理と態度理論への数理アプローチ,松香堂.
- 小杉考司・藤澤隆史・渡邊太・清水裕士・石盛真徳(編著)藤澤等(監修)(2006).ソシオン理論入門北大路書房．
- 関阪千里(著)・ソシオンジュニア研究会(監修)(2006).カトリーヌちゃんのサイコロ北大路書房．
- 小杉考司(2007).社会調査士のための多変量解析法北大路書房.
- 小杉考司・清水裕士(編著)(2014).M-plusとRによる構造方程式モデリング北大路書房.
- 小杉考司・押江隆(2014).Rチュートリアルセミナーテキスト.[http://goo.gl/BL5i8f](http://goo.gl/BL5i8f)
- 小杉考司(2018) 言葉と数式で理解する多変量解析入門,北大路書房.
- 小杉考司(2019) Rでらくらく心理統計 RStudio徹底活用 ,講談社サイエンティフィク.
- 小杉考司・紀ノ定保礼・清水裕士(2023).数値シミュレーションで読み解く統計のしくみ〜Rでためしてわかる心理統計,技術評論社

## 翻訳書

- 野波寛・岡本卓也・小杉考司(訳)(2010).集団間関係の社会心理学,晃洋書房.
- 小杉考司・高田菜美・山根嵩史(訳)(2016)研究論文を読み解くための多変量解析入門基礎篇◆重回帰分析からメタ分析まで,北大路書房.
- 小杉考司・高田菜美・山根嵩史(訳)(2016)研究論文を読み解くための多変量解析入門応用篇◆SEMから生存分析まで,北大路書房.
- 前田和寛・小杉考司(監訳)前田和寛・小杉考司・井関龍太・井上和哉・鬼田崇作・紀ノ定保礼・国里愛彦・坂本次郎・杣取恵太・高田菜美・竹林由武・徳岡大・難波修史・西田若葉・平川真・福屋いずみ・武藤杏里・山根嵩史・横山仁史(訳)(2017)ベイズ統計モデリング:R,JAGS,Stanによるチュートリアル,共立出版.
- 樫原潤・小杉考司(監訳)(2024)心理ネットワークアプローチ入門,勁草書房.

## 分担執筆

- 小杉考司(2006).売り手と買い手の取引ゲーム,藤原武弘(編)人間関係のゲーミング・シミュレーション,北大路書房,57-77.
- 小杉考司(2009).集団の静的構造,藤原武弘(編)社会心理学,晃洋書房,146-158.
- 小杉考司(2009).情報行動,藤原武弘(編)社会心理学,晃洋書房,193-204.
- 小杉考司(2012).社会心理学における帰属概念について研究指導を通して理解する,福田廣・名島潤慈(監修)田邊敏明（編）心理学へのいざない,北大路書房,28-45.
- 小杉考司(2018).心の旅が始まる--観光のイメージの世代間比較--,豊田秀樹(編) たのしいベイズモデリング,北大路書房,68--78.
- 小杉考司(2019).そのほかの多変量解析,繁桝算男・山田剛史(編) 公認心理師の基礎と実践5・心理学統計法,遠見書房,189--206.

## 学術論文（査読あり）

- 小杉考司・藤澤隆史・水谷聡秀・石盛真徳(2001).ダイナミック社会的インパクト理論における意見の空間的収束を生み出す要因の検討実験社会心理学研究,**41**,16-25.
- 野波寛・加藤潤三・池内裕美・小杉考司(2002).共有財としての河川に対する環境団体員と一般住民の集合行為：個人行動と集団行動の規定因社会心理学研究,**17**,123-135.
- Kosugi,K.,Kato,J.,Fujihara,T.(2003).The Effect of Commitment to a festival on attitude toward the in-group and out-group.*Social Behavior and Personality*,**31**,181-190.
- 小杉考司・藤原武弘(2004).等高線マッピングによる態度布置モデル行動計量学,**31**,17-24.
- 小杉考司・藤澤隆史・藤原武弘(2004).バランス理論と固有値分解理論と方法,**19**,87-100.
- Okamoto,T.,Fujihara,T.,Kato,J.,Kosugi,K.,Nakazato,N.,Hayashi,Y.,Ikeuchi,H.,Nakagawa,N.,Mori,K.and Nonami,H.(2005).Measuring Social Stereotypes with Photo Projective Method,*Social Behavior and Personality*,**34**,319-332.
- 石盛真徳・藤澤隆史・小杉考司・清水裕士・渡邊太・藤澤等(2008).家族システムの構造分析--家族成員間関係と家族全体システムの機能との関連性について--バイオメディカル・ファジィ・システム学会誌,**10**,159-168．
- 清水裕士・小杉考司(2010).対人行動の適切性判断と社会規範—「社会関係の論理学」の構築—実験社会心理学研究,**49**,132-148.
- 小杉考司・清水裕士・藤澤隆史・石盛真徳・渡邊太・藤澤等(2011).家族関係尺度における階層的因子構造について,行動計量学,**38**,93-99.
- 川本静香・小杉考司(2012).ブートストラップ法を用いた抑うつ概念における類型論的アプローチ,立命館人間科学研究,**25**,109-113.
- 川本静香・渡邉卓也・小杉考司・村尾幸治・渡邉義文・サトウタツヤ(2014).うつ病アナログ群の特徴について--抑うつの連続政検討の観点から,パーソナリティ研究,23(1),1-12.
- 石盛真徳・小杉考司・清水裕士・藤澤隆史・渡邊太・武藤杏里(2017)マルチレベル構造方程式モデリングによる夫婦ペアデータへのアプローチ：中年期の夫婦関係のあり方が夫婦関係満足度，家族の安定性，および主観的幸福感に及ぼす影響，実験社会心理学研究,**56**,2,153-164.
- Kosugi,K.E(2017)Asymmetrical triadic relationship based on the structural difficulty.*Behaviormetrika*,**45(1)**,7--23.
- 永野駿太・木本茉莉奈・小杉考司・小野史典(2018)透明性の錯覚に与える解の既知性の影響,行動計量学,**45**(1),59--66.
- Trafimow David, Amrhein Valentin, Areshenkoff Corson N., Barrera-Causil Carlos J., Beh Eric J., Bilgiç Yusuf K., Bono Roser, Bradley Michael T., Briggs William M., Cepeda-Freyre Héctor A., Chaigneau Sergio E., Ciocca Daniel R., Correa Juan C., Cousineau Denis, de Boer Michiel R., Dhar Subhra S., Dolgov Igor, Gómez-Benito Juana, Grendar Marian, Grice James W., Guerrero-Gimenez Martin E., Gutiérrez Andrés, Huedo-Medina Tania B., Jaffe Klaus, Janyan Armina, Karimnezhad Ali, Korner-Nievergelt Fränzi, Kosugi Koji, Lachmair Martin, Ledesma Rubén D., Limongi Roberto, Liuzza Marco T., Lombardo Rosaria, Marks Michael J., Meinlschmidt Gunther, Nalborczyk Ladislas, Nguyen Hung T., Ospina Raydonal, Perezgonzalez Jose D., Pfister Roland, Rahona Juan J., Rodríguez-Medina David A., Romão Xavier, Ruiz-Fernández Susana, Suarez Isabel, Tegethoff Marion, Tejo Mauricio, van de Schoot Rens, Vankov Ivan I., Velasco-Forero Santiago, Wang Tonghui, Yamada Yuki, Zoppino Felipe C. M., Marmolejo-Ramos Fernando (2018) Manipulating the Alpha Level Cannot Cure Significance Testing,*Frontiers in Psychology*,**9**,699.
- Yonemitsu, F., Sasaki, K., Gobara, A., Kosugi, K., & Yamada, Y. (2018). ‘‘Close, and ye shall find’’: eye closure during thinking enhances creativity. *Palgrave Communications*, 4(1), 80.
- 林幸史・小杉考司(2018) 過去の旅行経験から見た観光地イメージ,社会心理学研究,**34**(1),38-46.
- 小杉考司(2019).学習管理システムのアクセス記録から学業成績を予測する,専修人間科学論集心理学編,**9**(1),1--7.
- 山南 春奈・長島 愛・中村 潤・田中 奈津子・小杉考司(2021)男性版顔立ちマップの開発と眉による印象演出の効果,日本顔学会誌,**21**(2),71--83.
- 小杉考司(2023)心理尺度の開発と利用における問題の所在,専修人間科学論集心理学編,**13**(1),39--49.
- 小林美月・野村圭史・小杉考司(2025)潜在意味スケーリングを用いて付与した感情極性値による不満度の予測,専修人間科学論集心理学編,**15**(1),25--35.

## 学術論文（査読なし）

- Kosugi,K.,Fujihara,T.and Ikeuchi,H.(2000).A study of the risk perception of information leakage in a computer-mediated society(3).関西学院大学社会学部紀要,**84**,181-188.
- 小杉考司(2000).ソシオグラムによる職場集団の多重構造の把握国際経済労働研究,**55**,16-21.
- 水谷聡秀・小杉考司・藤澤隆史(2002).計算論的ソシオンモデルのシミュレーション--二者関係と三者関係による好悪荷重の変化--関西大学大学院「人間科学」,**57**,109-132.
- 藤澤隆史・小杉考司・水谷聡秀(2002).計算論的ソシオンモデルのシミュレーション(2)--トライアッドの転移オペレーションと荷重バランスの検討--関西大学大学院「人間科学」,**58**,133-147.
- 石盛真徳・藤澤隆史・小杉考司(2002).集団現象へのセル・オートマトン的アプローチ対人社会心理学研究,**2**,111-117.
- 藤原武弘・小杉考司(2005).社会的ネットワークの多次元的解析関西学院大学社会学部紀要,**98**,33-41.
- 小杉考司(2008).EASY調査項目の精緻化に向けて--中学校生活に対する期待と不安の調査データの再分析--山口大学心理臨床研究,**8**,13-25.
- 福田廣・福本純一・小杉考司(2009).ひったくり犯罪における発生要因の多変量解析山口大学教育学部研究論叢第3部,**58**,287-295.
- 若藤夏子・小杉考司(2009).投影法「絵画感想法」の構成とテキストマイニング・アプローチ山口大学心理臨床研究,**9**,19-30.
- 沖林洋平・山崎茜・山田洋平・小杉考司(2009).青年期における仲間関係イメージと仲間関係構築の関係山口大学心理臨床研究,**9**,11-18.
- 小杉考司・福田廣・恒吉徹三・沖林洋平(2010).心理学教育におけるFD実践事例報告・リレー講義の試み山口大学教育学部研究論叢第3部,**59**,79-83．
- 小杉考司(2010).小中学校における不登校問題のパターン分析山口大学教育学研究科付属臨床心理センター紀要,**1**,25-32.
- 沖林洋平・溝辺絵利香・三巻祐佳・富田英司・田村恭久・小杉考司(2010).心理学授業の内容理解における批判的思考態度のレディネスの効果山口大学教育学研究科付属臨床心理センター紀要,**1**,33—39.
- 小杉考司・渡辺成(2011).現代学生の規範意識と態度(1)山口大学教育学部研究論叢第3部,**60**,99-108．
- 渡辺成・小杉考司・大石英史(2011).現代の若者における職業選択モデルの構築山口大学教育学部研究論叢第3部,**60**,49-60.
- Kawamoto,S. and Kosugi,K.(2011).Classifying depression in university students by using the latent structure model.山口大学教育学部研究論叢第3部,**60**,109-114.
- 小杉考司(2012).現代学生の規範意識と態度(2)山口大学教育学部研究論叢第3部,**61**,113-122.
- Ikeda,M. and Kosugi,K.(2012).Surveillance studies of attitudes toward juvenile delinquency.山口大学教育学部研究論叢第3部,**61**,123-130.
- 日高美咲・小杉考司(2012).看板メッセージの印象が受け手の行動に与える影響.山口大学教育学部研究論叢第3部,**61**,131-136.
- 小杉考司(2013).現代学生の規範意識と態度(3).山口大学教育学部研究論叢第3部,**62**,119-123.
- 小杉考司・石盛真徳・清水裕士・渡邊太・藤澤隆史(2013).ソシオン譜による人間関係の描画について.山口大学教育学部研究論叢第3部,**62**,125-137.
- 日高美咲・小杉考司(2013).「空気を読む」という表現の社会心理学的研究.山口大学教育学部研究論叢第3部,**62**,139-144.
- 大山薫・小杉考司・恒吉徹三(2013).「信頼」と「安心」の言葉のイメージの差異について.山口大学教育学部附属教育実践総合センター研究紀要,**35**,71-78.
- 小杉考司(2015)学校適応感尺度FITの開発,山口大学教育学部研究論叢第3部,**64**,69--82.
- 小杉考司・川崎徳子・恒吉徹三・小野史典・押江隆・沖林洋平(2015)講義によって心理学に対する印象はどのように変化するのか,山口大学教育学部研究論叢第3部,**64**,83--91.
- 小杉考司・藤原武弘(2015)社会的態度の三次元力場モデル--補間モデルの比較による検証--,関西学院大学社会学部紀要,**120**,125--131.
- 片桐咲恵・西村太志・古谷嘉一朗・相馬敏彦・小杉考司(2017)子育て中の母親はどのようにして対人関係を広げるのか?--「社会的代理人」利用状況の自由記述を用いた探索的研究,山口大学教育学部研究論叢第3部,**66**,83--94.
- 本田志穂・石丸彩香・宇津宮沙紀・山根倫也・小田美優・坂本和久・大江慶寛・小林仁美・有馬多久充・木寺碧・小杉考司(2017)日本人にとって道徳はどのようなものとしてとらえられているか--新しい道徳基盤尺度項目の開発を通じた検証--,山口大学教育学部研究論叢第3部,**66**,95--106.
- 小杉考司(2019)新しい統計学とのつきあい方,基礎心理学研究,37(2),167--173.
- 小杉考司(2019)多次元尺度構成法--その基礎と広がり--,認知心理学会テクニカルレポート.
- 小杉考司(2019)ベイズ統計を用いた有意性検定からの脱却,社会と調査,23,92--98.
- 小杉考司(2019)ベイズで広がるモデリングの世界,理論と方法,34(2),326--337.

## 学会発表

- 喜多将司・藤澤隆史・小杉考司・藤澤等,境界と集団の生成過程(I),日本社会心理学会,1997.9.5,立教大学(東京都豊島区)
- 藤澤隆史・小杉考司・喜多将司・藤澤等,境界と集団の生成過程(II),日本社会心理学会,1997.9.5,立教大学(東京都豊島区)
- 小杉考司・喜多将司・藤澤隆史・藤澤等,境界と集団の生成過程(III),日本社会心理学会,1997.9.5,立教大学(東京都豊島区)
- Kosugi,K., Fujihara, T and Ikeuchi,H., A study of the risk perception of a leakage of information in a computer-mediated society, Asian Association of Social Psychology,1999.8.4,Taiwan,Taipei
- Kosugi,K., Fujihara, T. and Fujisawa,H., An Analysis of Sociometric Data by using Socion Model, International Congress of Psychology,2000.7.27,Sweden,Stockholm
- 加藤潤三・小杉考司・野波寛・藤原武弘,仮想世界ゲームにおけるコモンズと集団アイデンティティ－きっかけとしてのコモンズ－,日本グループ・ダイナミックス学会,2000.9.30,東洋大学(東京都文京区)
- 小杉考司・藤原武弘,ソシオメトリックデータに対する非対称多次元尺度構成法の適用,日本社会心理学会,2000.11.3,関西大学(大阪府大阪市)
- 小杉考司・加藤潤三・藤原武弘,祭りで魅力ある地域を作る～集団内態度と集団間態度の縦断的分析～,日本グループ・ダイナミックス学会,2001.10.27,熊本大学(熊本県熊本市)
- 加藤潤三・小杉考司・野波寛・藤原武弘,仮想世界ゲームにおける集団間葛藤－共通課題は仲を悪くする？－,日本グループ・ダイナミックス学会,2001.10.28,熊本大学(熊本県熊本市)
- 小杉考司・藤澤隆史・藤原武弘,三者関係パターンにおける関係性の推測～適合度・一致度を指標とした推測方法の比較～,日本社会心理学会,2002.11.9,一橋大学(東京都国立市)
- 加藤潤三・岡本卓也・小杉考司・野波寛,仮想世界ゲームにおける集団間の衡平性－主観的衡平性と客観的衡平性－,日本社会心理学会,2002.11.10,一橋大学(東京都国立市)
- 藤澤隆史・小杉考司,複数の自律エージェントによる協調作業シミュレーション－タスク環境の構造に導かれた行動パターン－,日本社会心理学会,2002.11.10,一橋大学(東京都国立市)
- 藤澤隆史・小杉考司,バランス理論と固有値分解(1),日本グループ・ダイナミックス学会,2003.3.22,キャンパスプラザ京都(京都府，京都市)
- 小杉考司・藤澤隆史,バランス理論と固有値分解(2),日本グループ・ダイナミックス学会,2003.3.22,キャンパスプラザ京都(京都府，京都市)
- 小杉考司・藤原武弘,等高線マップモデルによる態度の表現,日本グループ・ダイナミックス学会,2004.5.8,南山大学(愛知県名古屋市)
- 石盛真徳・藤澤隆史・小杉考司・藤澤等,社会関係データとその分析法-MatrixRevolutions-,日本グループ・ダイナミックス学会,2004.5.8,南山大学(愛知県名古屋市)
- 藤原武弘・小杉考司・加藤潤三・中里直樹・岡本卓也,写真投影法による社会的アイデンティティの測定(1),日本グループ・ダイナミックス学会,2004.5.8,南山大学(愛知県名古屋市)
- 小杉考司・藤澤隆史・藤原武弘,バランス理論と固有値分解(3),日本社会心理学会,2004.7.18,北星大学(北海道札幌市)
- 雨宮俊彦・藤澤等・小杉考司・藤澤隆史・水谷聡秀・石盛真徳・木村洋二・渡邊太,ソシオン理論の展望―-アイデアから研究プロジェクトへ―,日本心理学会,2004.9.14,関西大学(大阪府吹田市)
- 小杉考司・藤原武弘,等高線マップモデルによる態度構造の統合的表現,日本グループ・ダイナミックス学会,2005.9.25,関西学院大学(兵庫県西宮市)
- 藤澤隆史・小杉考司・石盛真徳・清水裕士・渡邊太・藤澤等,家族コミュニケーションの構造分析(1),日本社会心理学会,2006.5.27,武蔵野大学(東京都西東京市)
- 石盛真徳・藤澤隆史・小杉考司・清水裕士・渡邊太・藤澤等,家族コミュニケーションの構造分析(2),日本グループ・ダイナミックス学会,2006.5.27,武蔵野大学(東京都西東京市)
- 小杉考司・石盛真徳・藤澤隆史・清水裕士・渡邊太・藤澤等,家族コミュニケーションの構造分析(3),日本グループ・ダイナミックス学会,2006.5.27,武蔵野大学(東京都西東京市)
- Kosugi,K.,and Fujihara,T, Cognitive Strategy in Learning Triadic Interpersonal Relationships,International Congress of Applied Psychology,2006.7.19,Greece,Athens.
- 小杉考司,三人ゲームの理論的考察(1)－Kelleyの相互依存性理論による影響力の分解－,日本社会心理学会,2006.9.18,東北大学(宮城県仙台市)
- 小杉考司・清水裕士・藤澤隆史,Pop音楽におけるコード進行の構造とその認知(1),日本心理学会,2006.11.4,福岡国際会議場(福岡県福岡市)
- 清水裕士・小杉考司・藤澤隆史,Pop音楽におけるコード進行の構造とその認知(2),日本心理学会,2006.11.4,福岡国際会議場(福岡県福岡市)
- 清水裕士・小杉考司,葛藤解決法略としての社会規範－相互依存性理論に基づく理論的考察－,日本グループ・ダイナミックス学会,2007.6.17,名古屋大学(愛知県名古屋市)
- Kosugi,E.K.,Shimizu,N.H.,Fujisawa,X.T.,Ishimori,M.Watanabe,F.and Fujisawa,H.,Scaling for Family Relationships Based on Socion Theory by Using a Three-mode Item Response Model.,Psychometric Society,2007.7.12,タワーホール船堀(東京都江戸川区)
- Maemura,N.,Kosugi,E.K. and Fujihara,T, The Development of an Empathic Ability Scale by using the Item Response Theory.,Psychometric Society,2007.7.12,タワーホール船堀(東京都江戸川区)
- 福本純一・小杉考司・福田廣・松野凱典,窃盗犯のプロフィールと犯行手口の質的分析,日本応用心理学会,2007.9.8,帝塚山大学(奈良県奈良市)
- 前村奈央佳・小杉考司・藤原武弘,共感力と心理的距離の関連性について,日本応用心理学会,2007.9.23,早稲田大学(東京都新宿区)
- 小杉考司・福田廣,防犯・防災に対するリスク認知とリスクコントロール尺度の作成,九州心理学会,2007.11.10,別府国際コンベンションセンター(大分県別府市)
- 小杉考司・清水裕士,三人ゲームの理論的考察（２）－パレート解としての葛藤解決法略－,日本グループ・ダイナミックス学会,2008.6.14,広島大学(広島県東広島市)
- 藤澤隆史・小杉考司・清水裕士,非対称MDSを用いた楽曲のコード進行の分析,日本行動計量学会,2008.9.5,成蹊大学(東京都武蔵野市)
- 小野修一・福田廣・小杉考司・大浜強志・福本純一・松野凱典,防犯・防災に対するリスク認知について(1),日本応用心理学会,2008.9.14,横浜国立大学(神奈川県横浜市)
- 小杉考司・小野修一・福田廣・大浜強志・福本純一・松野凱典,防犯・防災に対するリスク認知について(2),日本応用心理学会,2008.9.14,横浜国立大学(神奈川県横浜市)
- 小杉考司・沖林洋平・恒吉徹三・福田廣,テスト成績と授業評価から見た「リレー講義」(2)－共通教育「心理学」における実践事例－,大学教育研究フォーラム,2009.3.21,京都大学高等教育研究開発推進センター(京都府京都市)
- 藤澤隆史・小杉考司・清水裕士・石盛真徳・渡邉太・藤澤等,家族コミュニケーションの構造分析(6)精神的健康との関連性の検討,日本心理学会,2009.8.28,立命館大学(京都府京都市)
- 清水裕士・藤澤隆史・小杉考司・渡邉太・石盛真徳・藤澤等,家族コミュニケーションの構造分析(5)マルチレベルモデルによる二相三元非対称データの分析,日本心理学会,2009.8.28,立命館大学(京都府京都市)
- 小杉考司・清水裕士・藤澤隆史・渡邉太・藤澤等・石盛真徳,家族コミュニケーションの構造分析(4)～多相データの二段階分析とコミュニケーション構造～,日本心理学会,2009.8.28,立命館大学(京都府京都市)
- 清水裕士・藤澤隆史・小杉考司・渡邊太・石盛真徳・藤澤等,家族関係における階層的非対称データの分析-MultilevelSocialRelationsModelによる検討-,日本行動計量学会,2009.8.6,大分大学(大分県大分市)
- 小杉考司・清水裕士,現代大学生の倫理意識研究(1),日本社会心理学会,2009.10.12,大阪大学(大阪府吹田市)
- 渡辺成・小杉考司,現代の若者における職業選択モデルの構築－生活意識及び職業価値観に焦点化して－,日本社会心理学会,2009.10.12,大阪大学(大阪府吹田市)
- 福本純一・小杉考司・福田廣・松野凱典・恒吉徹三・沖林洋平・大浜強志・渋谷友祐・小野修一,街頭犯罪についてのリスク認知と防犯行動の関連(2),中国四国心理学会,2009.10.24,香川大学(香川県高松市)
- 小杉考司・福本純一・福田廣・松野凱典・恒吉徹三・沖林洋平・大浜強志・渋谷友祐・小野修一,街頭犯罪についてのリスク認知と防犯行動の関連(1),中国四国心理学会,2009.10.24,香川大学(香川県高松市)
- 小杉考司・福田廣,街頭犯罪についてのリスク認知と防犯行動の関連(3),九州心理学会,2009.12.5,佐賀大学(佐賀県佐賀市)
- Kosugi,K.,Okibayashi,Y.and Fukuda,H.,A surveillance study for a street crime prevention intervention,International Congress of Applied Psychology,2010.7.12,Melbourne,Australia.
- Okibayashi,Y.,Kosugi,K.and Fukuda,H.,Surveillance study for intervention to prevention of street crime,International Congress of Applied Psychology,2010.7.13,Melbourne,Australia.
- 小杉考司,不登校児童の早期発見に向けた調査研究(2),日本グループ・ダイナミックス学会,2010.8.28,東京国際大学(埼玉県川越市)
- 小杉考司・福本純一・福田廣・沖林洋平,求める犯罪報道内容とその心理・地理的要因,日本応用心理学会,2010.9.12,京都大学(京都府京都市)
- 小杉考司,不登校児童の早期発見に向けた調査研究：EASYの活用について,日本心理学会,2010.9.21,大阪大学(大阪府吹田市)
- 小杉考司・藤澤隆史・清水裕士・石盛真徳・渡邊太・藤澤等,家族関係データに対する非対称MDSの応用,日本行動計量学会,2010.9.23,埼玉大学(埼玉県さいたま市)
- 沖林洋平・小杉考司・福田廣,街頭犯罪についてのリスク認知と防犯行動の関連(4）,九州心理学会,2010.11.7,長崎大学(長崎県長崎市)
- 小杉考司・沖林洋平・福田廣,街頭犯罪についてのリスク認知と防犯行動の関連(5）,九州心理学会,2010.11.7,長崎大学(長崎県長崎市)
- 福田廣・小杉考司・福本純一・沖林洋平,求める犯罪報道内容とその心理・地理的要因(2),中国四国心理学会,2010.11.13,鳥取大学(鳥取県米子市)
- 小杉考司・福田廣・福本純一・沖林洋平,求める犯罪報道内容とその心理・地理的要因(3),中国四国心理学会,2010.11.13,鳥取大学(鳥取県米子市)
- Kosugi,K.,Fujisawa,T.and Shimizu,H.,Verification of the Moral Foundations Theory in Japan.,European congress of Psychology,2011.7.5,Istanbul,Turkey.
- Okibayashi,Y.,Kawamoto,S.,Kosugi,K.and Ohishi,E.,Development the scale to Measure the characteristics of Non-attendant Children,European congress of Psychology,2011.7.5,Istanbul,Turkey.
- 小杉考司・池田正博・沖林洋平・福田廣,求める犯罪報道内容とその心理・地理的要因(4),日本グループ・ダイナミックス学会,2011.8.24,昭和女子大学(東京都世田谷区)
- 池田正博・小杉考司・福田廣・沖林洋平・福本純一,少年犯罪に対する態度形成要因(2),日本応用心理学会,2011.9.10,信州大学(長野県松本市)
- 小杉考司・池田正博・福田廣・沖林洋平・福本純一,少年犯罪に対する態度形成要因(3),日本応用心理学会,2011.9.10,信州大学(長野県松本市)
- 小杉考司,不登校児童の早期発見に向けた調査研究(3),日本心理学会,2011.9.15,日本大学(東京都世田谷区)
- 川本静香・小杉考司,抑うつ尺度における因子構造の再検討,日本心理学会,2011.9.16,日本大学(東京都世田谷区)
- 池田正博・小杉考司・福田廣・沖林洋平,少年犯罪に対する態度形成要因(1),日本心理学会,2011.9.17,日本大学(東京都世田谷区)
- 小杉考司・池田正博・沖林洋平・福田廣,犯罪報道に対する態度に影響する要因を探る,日本社会心理学会,2011.9.18,名古屋大学(愛知県名古屋市)
- 池田正博・福田廣・小杉考司・沖林洋平,少年犯罪に対する態度形成要因(4),中国四国心理学会,2011.11.13,比治山大学(広島県広島市)
- 小杉考司,態度変容の三次元空間モデル(1),中国四国心理学会,2011.11.13,比治山大学(広島県広島市)
- 西田若葉・小杉考司・沖林洋平,アイデンティティ概念に含まれる要素の構造化および研究の変遷の検討,九州心理学会,2011.11.19,熊本大学(熊本県熊本市)
- 川本静香・小杉考司,抑うつ概念における類型論的アプローチの再検討―健常者とうつ病患者は本当に連続体なのか？－,九州心理学会,2011.11.19,熊本大学(熊本県熊本市)
- 小杉考司・川谷義隆,態度変容の三次元空間モデル(2),九州心理学会,2011.11.19,熊本大学(熊本県熊本市)
- 高田菜美・小杉考司,物語にみられる許しの促進要因,九州心理学会,2011.11.19,熊本大学(熊本県熊本市)
- 沖林洋平・小杉考司・池田正博・福田廣,どのような情報提供が計犯罪に対するリスク認知の変化に影響を及ぼすのか,九州心理学会,2011.11.19,熊本大学(熊本県熊本市)
- 高田菜美・小杉考司,新約聖書ごとのゆるし表現の違い,日本心理学会,2012.9.12,専修大学(神奈川県川崎市)
- 小杉考司・川谷義隆,非対称データの三次元空間モデル,日本行動計量学会,2012.9.15,新潟県立大学(新潟県新潟市)
- 高田菜美・小杉考司,旧約聖書ごとのゆるし表現の違い,九州心理学会,2012.11.10,鹿児島大学(鹿児島県鹿児島市)
- 川谷義隆・小杉考司,態度変容の三次元空間モデル(4),九州心理学会,2012.11.11,鹿児島大学(鹿児島県鹿児島市)
- 松沼風子・池田正博・日高美咲・小杉考司,新学校適応感尺度FITの妥当性の検証(1),日本教育心理学会,2012.11.23,琉球大学(沖縄県中頭郡)
- 池田正博・日高美咲・松沼風子・小杉考司,新学校適応感尺度FIT高校生版の開発,日本教育心理学会,2012.11.23,琉球大学(沖縄県中頭郡)
- 小杉考司・藤澤隆史・清水裕士・石盛真徳・渡邊太・藤澤等,家族関係データに対する非対称MDSの応用,日本行動計量学会,2013.9.6,東邦大学(東京都大田区)
- 石盛真徳・小杉考司・清水裕士・藤澤隆史・渡邊太,家族システムの発達と移行に関する研究(1)—父親と母親のネット利用の積極性と夫婦間・家族内コミュニケーションおよび地域コミュニティでの参加・交流との関連—,日本心理学会,2013.9.21,札幌コンベンションセンター(北海道札幌市)
- 小杉考司・石盛真徳・清水裕士・藤澤隆史・渡邊太,家族システムの発達と移行に関する研究(2),日本心理学会,2013.9.21,札幌コンベンションセンター(北海道札幌市)
- 小杉考司・岡本卓也,態度変容の三次元空間モデル(5)－縦断的ソシオメトリックデータの分析例－,日本社会心理学会,2013.11.2,沖縄国際大学(沖縄県宜野湾市)
- Tokuko Kawasaki,Koji Kosugi,Noyuri Endo and Rui Otsuka, Surveillance study of teacher's morality,International Congress of Applied Psychology,2014.7.11,France,Paris des congress.
- Mao KAMAATA,Takuya OKAMOTO and Koji E. Kosugi,Scaling for individual relations and visualizing samll group process(1),International Congress of Applied Psychology,2014.7.12,France,Paris des congress.
- Kosugi,E.Koji,Mao,KAMATA and Takuya Okamoto,Scaling for individual relations and visualizing samll group process(2)-Visualizing social interactions and psychological attitudes, International Congress of Applied Psychology,2014.7.12,France,Paris des congress.
- 林幸史・小杉考司.旅行経験による旅行者の類型化とその特徴,日本社会心理学会,2014.07.27,北海道大学(北海道札幌市)
- 小杉考司・林幸史(2014).多層データの三次元モデルについて,日本行動計量学会,2014.09.03,東北大学(宮城県仙台市)
- 小杉考司・林幸史(2014).旅行経験による旅行者の類型と地理的イメージの違い,日本グループ・ダイナミックス学会,2014.09.07,東洋大学(東京都文京区)
- 石盛真徳・小杉考司・清水裕士・藤澤隆史・渡邊太(2014).家族システムの発達と移行に関する研究(3)--夫婦ペアデータのマルチレベル相関分析--,日本グループ・ダイナミックス学会,2014.09.07,東洋大学(東京都文京区)
- 小杉考司・藤澤隆史・藤澤等(2014).認知的経済性に基づく集団内クラスタリング,日本心理学会,2014.09.11,同志社大学(京都府京都市)
- 藤澤隆史・小杉考司・藤澤等(2014).認知的経済性の個人差とメンタルヘルス,日本心理学会,2014.09.11,同志社大学(京都府京都市)
- 村尾美幸・小野史典・小杉考司,日本人が持つひらがなの心的空間表象の検討,九州心理学会,2014.11.15,宮崎公立大学(宮崎県宮崎市)
- 小杉考司・林幸史,旅行者特性ごとに見た観光地イメージの違いについて,九州心理学会,2014.11.15,宮崎公立大学(宮崎県宮崎市)
- Tokuko KAWASAKI and Koji E. Kosugi, Influence of kindergarten teachers’morality on educational programs,European congress of Psychology,2015.7.8,Milan.Italy
- Koji E. Kosugi,Three dimensional Force Field Model for individual preference,European congress of Psychology,2015.7.8,Milan.Italy
- 石盛真徳・小杉考司・清水裕士・藤澤隆史・渡邊太,家族システムの発達と移行に関する研究(4),日本心理学会,2015.9.22,名古屋国際会議場(愛知県名古屋市)
- 藤澤隆史・清水裕士・小杉考司・石盛真徳・渡邊太,家族システムの発達と移行に関する研究(5),日本心理学会,2015.9.22,名古屋国際会議場(愛知県名古屋市)
- 小杉考司・清水裕士・石盛真徳・藤澤隆史・渡邊太,家族システムの発達と移行に関する研究(6),日本心理学会,2015.9.22,名古屋国際会議場(愛知県名古屋市)
- 清水裕士・石盛真徳・小杉考司・藤澤隆史・渡邊太,家族システムの発達と移行に関する研究(7),日本心理学会,2015.9.22,名古屋国際会議場(愛知県名古屋市)
- 小杉考司・清水裕士・平川真,印象形成における評定者・被評定者とベイズ推定,日本グループ・ダイナミックス学会,2015.10.12,奈良大学(奈良県奈良市)
- 小杉考司・林幸史,観光行動に影響する知覚された誘因の検討,日本社会心理学会,2015.10.31,東京女子大学(東京都杉並区)
- 本田志穂・小野史典・小杉考司,書字行為が自尊感情に与える影響,九州心理学会,2015.11.14,大分県立芸術短期大学(大分県大分市)
- 石丸彩香・小杉考司・小野史典,被害者と加害者の身体的魅力度が量刑判断に及ぼす影響,九州心理学会,2015.11.14,大分県立芸術短期大学(大分県大分市)
- Shiho Honda,Koji E. Kosugi,Sayaka Ishimaru, Saki Utsunomiya, Tomonari Yamane, Kazuhisa Sakamoto, Yoshihiro Ohe, Hitomi Kobayashi, Takumi Arima and Aoi Kidera, Development of a Japanese version of the Moral Foundation Questionnaire, International Congress of Psychology,2016.7.27.,パシフィコ横浜（神奈川県横浜市）
- 小杉考司・清水裕士,探索的因子分析のベイズ推定について；MCMCサンプリング方と変分ベイズ方の長短所,行動計量学会,2016.9.1,札幌学院大学(北海道江別市)
- 小杉考司・清水裕士・水谷聡秀・武藤杏里・平川真,二者関係と三者関係の影響力の大きさを比較する,社会心理学会,2016.9.17,関西学院大学(兵庫県西宮市)
- 永野駿太・小杉考司・小野史典,楽しい考えは笑顔から--思考抑制に与える表情操作の影響--,中国四国心理学会,2016.10.29,東亜大学(山口県下関市)
- 片桐咲恵・西村太志・小杉考司,子育て中の母親のネットワーク構築過程の検討--「社会的代理人」利用に関する自由記述を用いて--,中国四国心理学会,2016.10.30,東亜大学(山口県下関市)
- 矢野慶次郎・小杉考司,青年期後期の家族役割と子どもの主観的幸福感の関係について,九州心理学会,2016.12.03,西南学院大学(福岡県福岡市)
- 本田志穂・小杉考司,LINEグループにおける社会的ジレンマ構造の検討,九州心理学会,2016.12.03,西南学院大学(福岡県福岡市)
- 大江慶寛・小杉考司,集団意思決定における適正人数の検討,九州心理学会,2016.12.03,西南学院大学(福岡県福岡市)
- 小林仁美・小杉考司,お菓子を食べることが課題成績に与える影響,九州心理学会,2016.12.04,西南学院大学(福岡県福岡市)
- Tokuko Kawasaki,Koji Kosugi,Fuminori Ono, Eiji Oishi, Noyuri Endo, Rui Otsuka, Concerning the potential for formal education to support the development of social skills in Japanese young people., Asian Association of Social Psychology,2017.08.27,Auckland(New Zealand)
- Koji Kosugi,Tokuko Kawasaki,Eiji Oishi, Fuminori Ono, Takashi Oshie, A study of basic skills which need to be included in career education programs at university., Asian Association of Social Psychology,2017.08.28,Auckland(New Zealand)
- 清水裕士・小杉考司,多次元展開法を用いた非対称な人間関係の可視化,日本行動計量学会,2017.09.01,静岡県立大学(静岡県静岡市)
- 小杉考司・清水　裕士・石盛　真徳・藤澤　隆史・武藤　杏里・平川　真,家族成員の相互評定に含まれる偏向を推定する,日本社会心理学会,2017.10.29,広島大学(広島県東広島市)
- 大江慶寛・小杉考司,ベイズの定理は人の確率推論モデルになり得るか,中国四国心理学会,2017.11.11,徳島大学(徳島県徳島市)
- 片桐咲恵・西村大志・小杉考司,子育て中の母親の個人特性とネットワーク構築過程の検討-「社会的代理人」利用に関する自由記述を用いて(2)-,中国四国心理学会,2017.11.11,徳島大学(徳島県徳島市)
- 本田志穂・小宮あすか・中西大輔小杉考司,LINEのグループトークにおける頻度依存戦略の検討,中国四国心理学会,2017.11.11,徳島大学(徳島県徳島市)
- 大江慶寛・小杉考司,個人間の物理的位置関係と心理的位置関係における相互作用の検討,九州心理学会,2017.12.09,佐賀大学(佐賀県佐賀市)
- 有馬多久充・小杉考司,表示媒体が記憶と文章理解に与える影響,九州心理学会,2017.12.10,佐賀大学(佐賀県佐賀市)
- 濱咲里紗・小杉考司,人数比率と人数差が説得する意思に及ぼす影響,九州心理学会,2017.12.10,佐賀大学(佐賀県佐賀市)
- 本田志穂・小宮あすか・中西大輔・小杉考司,集団意思決定のゲーム構造が LINE の返信行動に及ぼす影響,日本社会心理学会,2018.08.28.,追手門学院大学(大阪府高槻市)
- 安藤正和・小杉考司,日常的購買行動におけるセールスプロモーション効果の推定：値引きとポイント付与から見たマグニチュード効果の検証,中国四国心理学会,2018.10.13,東広島市市民文化センター（広島県東広島市）
- 平川真・小杉考司,他者の態度についての信念の更新--他者の態度情報を提示することの効果--,中国四国心理学会,2018.10.14,東広島市市民文化センター（広島県東広島市）
- 越智宏明・小杉考司,ベイジアンERGMによるコミュニケーションネットワーク構造分析,行動計量学会,2019.09.06,大阪大学豊中キャンパス（大阪府豊中市）
- 池田孝恒・小杉考司,ソシオメトリックデータに対する FunctionalMDS の適用,行動計量学会,2019.09.06,大阪大学豊中キャンパス（大阪府豊中市）
- 安藤正和・小杉考司,購買金額変動に伴うセールスプロモーション効果の推定,九州心理学会,2019.11.17,熊本大学黒髪キャンパス（熊本県熊本市）
- Masakazu Ando,Koji Kosugi,Price discounts vs. awarding points: Verification of sales promotion effect in Japanese supermarket.,The 2020 edition of the annual joint meeting of the Society for Mathematical Psychology and the International Conference on Cognitive Modeling,2017.07.20,Virtual.
- Hiroaki Ochi,Koji Kosugi,Advantages of TERGM compared to Siena.,The 2020 edition of the annual joint meeting of the Society for Mathematical Psychology and the International Conference on Cognitive Modeling,2017.07.20,Virtual.
- 安藤正和・小杉考司,値引きとポイント付与の統計モデリング--潜在クラスモデルを用いた傾向分析--,2020.09.01--09.04,早稲田大学富山キャンパス(東京都新宿区).(オンライン開催,抄録集p.20--23.)
- 小杉考司,対人関係の力動的変化のモデリング,2020.09.01--09.04,早稲田大学富山キャンパス(東京都新宿区).(オンライン開催,抄録集p.30--33.)
- 越智宏明・小杉考司,最後通牒ゲームにおける分配行動に第三者の存在が与える影響,社会心理学会,2021.08.26,帝京大学.オンライン開催.
- 小林美月・野村圭史・小杉考司,潜在意味尺度構成法を用いて付与した感情極性値による不満度の予測,日本心理学会,2024.09.06,熊本城ホール(熊本県熊本市).
- 上村大地・小杉考司,潜在意味分析を用いた自由記述の飽和率推定,日本心理学会,2024.09.06,熊本城ホール(熊本県熊本市).
- 小林美月・野村圭史・小杉考司,ドメインに特化した意味空間を用いた潜在意味尺度構成法の妥当性,行動計量学会,2024.09.13,大阪経済大学(大阪府大阪市),抄録集p.200-203.
- 上村大地・小杉考司,自由記述回答の飽和率推定における潜在意味分析を用いた分類と評定者による分類との比較,行動計量学会,2024.09.13,大阪経済大学(大阪府大阪市),抄録集p.204-207.
- 小杉考司・荘島宏二郎・清水裕士,多次元展開法を用いた多値バイクラスタリングモデルの提案,行動計量学会,2024.09.13,大阪経済大学(大阪府大阪市),抄録集p.232--235.
- Koji Kosugi,Kojiro Shojima, Extending biclustering models to polytomous psychological scales, IMPS2025,2025.7.15, Mineapolis, USA.
- Mizuki Kobayashi,Keishi Nomura, Koji Kosugi, Testing Russell's Affect Circumplex in Corpra: Latent Semantic Scaling Apploarch,IMPS2025,2025.7.15, Mineapolis, USA.
- 上村大地・小杉考司, 自由記述解答における飽和率推定法の比較：再捕獲法とLNREモデルの検討,行動計量学会,2025.08.30,専修大学生田キャンパス(神奈川県川崎市).
- 小林美月・野村圭史・小杉考司,単語埋め込みを用いた潜在意味スケーリングによる情動語の感情価-覚醒度平面上での可視化--Russell(1980)の円環モデルの概念的追試--,行動計量学会,2025.08.30,専修大学生田キャンパス(神奈川県川崎市).

## 外部資金

### 研究代表者として

- 小杉考司(2005.4-2007.3).三者関係における結託と孤立のゲーム理論的分析--合理的選択と心理的葛藤の最適戦略--,研究課題番号05J04409,科学研究費補助金(特別研究員奨励費).
- 小杉考司(2012.4-2016.3).空間統計学を用いた態度構造と態度変容の三次元モデルの構築,研究課題番号24730510,科学研究費補助金(若手研究(B)).
- 小杉考司(2016.4-2019.3).ベイズの定理から再構築する態度理論と集団形成過程,研究課題番号	16K13459，科学研究費補助金(挑戦的萌芽).
- 小杉考司(2019.4-2022.3).ベイズ推論と情報圧縮から広がる認知モデルの展開,研究課題番号 19K03211,科学研究費補助金(基盤(C)).
- 小杉考司(2024.4-2028.3).個人差を核とした心理尺度の理論と分析ツールの展開,研究課題番号 24K06481,科学研究費補助金(基盤(C)).

### 研究分担者として

- (研究代表者)福田廣,(2007.4-2008.3).ひったくり犯罪の発生状況と市民の恐怖感・リスク認知との乖離,社会安全研究財団2007年度一般研究助成.
- (研究代表者)福田廣,(2009.4-2011.3).街頭犯罪予防に向けたステーク・ホルダーへの実践的介入.研究課題番号21530729,科学研究費補助金(基盤(C)).
- (研究代表者)福田廣,(2010.4-2011.3).情報公開に関する構造モデルの作成：公開要求レベルと開示レベルの調和を目指して,社会安全研究財団2010年度一般研究助成.
- (研究代表者)大石英史,(2010.4-2013.3).効果的介入を目的とした不登校問題への包括的アプローチ,研究課題番号22530706,科学研究費補助金(基盤(C)).
- (研究代表者)石井眞治,(2011.4-2013.3).児童生徒の発達段階に対応した平和教育プログラムの開発と評価,研究課題番号23531269,科学研究費補助金(基盤(C)).
- (研究代表者)石盛真徳,(2012.4-2016.3).パネル調査に基づく家族システムの発達と移行に関する研究,研究課題番号24530799,科学研究費補助金(基盤(C)).
- (研究代表者)沖林洋平,(2012.4-2015.3).高次リテラシーとしての批判的読解力のアセスメントと教育実践,研究課題番号24530825,科学研究費補助金(基盤(C)).
- (研究代表者)川崎徳子,(2012.4-2015.3).道徳教育における他者視点の内在化を育む幼小連携プログラムの策定,研究課題番号24531009,科学研究費補助金(基盤(C)).
- (研究代表者)大石英史,(2015.4-2019.3).キャリア教育における多重多層型心理サポートプログラムの開発,研究課題番号15K04127,科学研究費補助金(基盤(C)).
- (研究代表者)川崎徳子,(2015.4-2018.3).「生活経験に基づいた実践的道徳教育」を導く教育環境モデルの開発と検証,研究課題番号15K01756,科学研究費補助金(基盤(C)).
- (研究代表者)福田廣,(2017.4-2021.3).嗜好性に対する統制感の錯覚モデルと錯覚是正プログラムの開発,研究課題番号17K04432,科学研究費補助金(基盤(C)).
- (研究代表者)林幸史,(2017.4-2021.3).旅行キャリア発達のための熟達化過程の解明とキャリア対応型観光支援システムの開発,研究課題番号17H02254,科学研究費補助金(基盤(B)).
- (研究代表者)澤幸祐,(2023.4-2026.3).表象力学の再興：随伴性判断における刺激表象と強化の力学的関係の解明,研究課題番号23K03018,科学研究費補助金(基盤(C)).
- (研究代表者)清水裕士(2024.4-2028.3).態度はいかにして測定されるべきか？態度測定を基礎づけるための理論的・実証的研究,研究課題番号 24K00481,科学研究費補助金(基盤(B)).

## 寄稿

- 小杉考司(2022)構造方程式モデリングの基礎,精神科,**41**(6),785--790.
